groups:
  - name: devs
    reviewers: 3
    usernames:
      - JorenSaeyTL
      - eniskraasniqi1
      - stefaandevylder
      - qubis741
      - lorgan3
      - BeirlaenAaron
      - driesd
      - lowiebenoot
      - farazatarodi
      - jelledc
      - KristofColpaert
