declare module '@teamleader/ui' {
  import { ReactNode, RefObject, HTMLAttributes, CSSProperties } from 'react';

  type SpacingProps = {
    margin: Unit;
    marginTop: Unit;
    marginRight: Unit;
    marginBottom: Unit;
    marginLeft: Unit;
    marginVertical: Unit;
    marginHorizontal: Unit;
    padding: Unit;
    paddingTop: Unit;
    paddingRight: Unit;
    paddingBottom: Unit;
    paddingLeft: Unit;
    paddingVertical: Unit;
    paddingHorizontal: Unit;
  };

  type LayoutProps = Pick<CSSProperties, 'display' | 'position' | 'alignItems' | 'justifyContent'>;

  type BoxProps = HTMLAttributes<HTMLDivElement> &
    Partial<SpacingProps> &
    Partial<LayoutProps> & {
      ref?: RefObject<HTMLDivElement>;
      backgroundColor?: string;
      backgroundTint?: string;
      children?: ReactNode;
    };

  export const AdvancedCollapsible: any;
  export const Avatar: any;
  export const AvatarStack: any;
  export const AsyncSelect: any;
  export const Badge: any;
  export const Banner: any;
  export const Box: any;
  export const Bullet: any;
  export const Button: any;
  export const ButtonGroup: any;
  export const Checkbox: any;
  export const CompactMessage: any;
  export const Counter: any;
  export const DataGrid: any;
  export const DatePicker: any;
  export const DatePickerInput: any;
  export const DatePickerRange: any;
  export const DatePickerInputRange: any;
  export const Dialog: any;
  export const DialogBase: any;
  export const EmptyPassport: any;
  export const ErrorText: any;
  export const Heading1: any;
  export const Heading2: any;
  export const Heading3: any;
  export const Heading4: any;
  export const Heading5: any;
  export const HelpText: any;
  export const Icon: any;
  export const IconButton: any;
  export const IconMenu: any;
  export const Input: any;
  export const InputBase: any;
  export const Island: any;
  export const IslandGroup: any;
  export const Label: any;
  export const Link: any;
  export const LoadingBar: any;
  export const LoadingMolecule: any;
  export const LoadingSpinner: any;
  export const Menu: any;
  export const MenuItem: any;
  export const MenuDivider: any;
  export const MenuTitle: any;
  export const Message: any;
  export const Monospaced: any;
  export const NumericInput: any;
  export const Overlay: any;
  export const Passport: any;
  export const Pagination: any;
  export const Popover: any;
  export const ProgressTracker: any;
  export const RadioButton: any;
  export const RadioGroup: any;
  export const ScrollContainer: any;
  export const Section: any;
  export const Select: any;
  export const SplitButton: any;
  export const StatusBullet: any;
  export const StatusLabel: any;
  export const TextBody: any;
  export const TextBodyCompact: any;
  export const TextDisplay: any;
  export const TextSmall: any;
  export const TabGroup: any;
  export const Tag: any;
  export const Textarea: any;
  export const TimeInput: any;
  export const TimerPulser: any;
  export const TitleTab: any;
  export const Toast: any;
  export const ToastContainer: any;
  export const Toggle: any;
  export const Tooltip: any;
  export const ValidationText: any;
  export const Widget: any;
  export const WysiwygEditor: any;
  export const QTip: any;
  export const COLOR: any;
  export const COLORS: any;
  export const TINTS: any;
  export const colorsWithout: any;
  export const tintsWithout: any;
  export const SIZES: any;
  export const sizesWithout: any;
  export const TINY: any;
  export const SMALL: any;
  export const MEDIUM: any;
  export const LARGE: any;
  export const FULLSCREEN: any;

  export type Unit = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
}
