'use strict';
var _interopRequireWildcard = require('@babel/runtime/helpers/interopRequireWildcard'),
  _interopRequireDefault = require('@babel/runtime/helpers/interopRequireDefault');
Object.defineProperty(exports, '__esModule', { value: !0 }), (exports.default = void 0);
var _extends2 = _interopRequireDefault(require('@babel/runtime/helpers/extends')),
  _objectSpread2 = _interopRequireDefault(require('@babel/runtime/helpers/objectSpread')),
  _objectWithoutProperties2 = _interopRequireDefault(require('@babel/runtime/helpers/objectWithoutProperties')),
  _classCallCheck2 = _interopRequireDefault(require('@babel/runtime/helpers/classCallCheck')),
  _createClass2 = _interopRequireDefault(require('@babel/runtime/helpers/createClass')),
  _possibleConstructorReturn2 = _interopRequireDefault(require('@babel/runtime/helpers/possibleConstructorReturn')),
  _getPrototypeOf3 = _interopRequireDefault(require('@babel/runtime/helpers/getPrototypeOf')),
  _assertThisInitialized2 = _interopRequireDefault(require('@babel/runtime/helpers/assertThisInitialized')),
  _inherits2 = _interopRequireDefault(require('@babel/runtime/helpers/inherits')),
  _defineProperty2 = _interopRequireDefault(require('@babel/runtime/helpers/defineProperty')),
  _react = _interopRequireWildcard(require('react')),
  _propTypes = _interopRequireDefault(require('prop-types')),
  _classnames = _interopRequireDefault(require('classnames')),
  _theme = _interopRequireDefault(require('./theme.css')),
  Box = (function(e) {
    function l() {
      var e, t;
      (0, _classCallCheck2.default)(this, l);
      for (var r = arguments.length, i = new Array(r), a = 0; a < r; a++) i[a] = arguments[a];
      return (
        (t = (0, _possibleConstructorReturn2.default)(
          this,
          (e = (0, _getPrototypeOf3.default)(l)).call.apply(e, [this].concat(i)),
        )),
        (0, _defineProperty2.default)((0, _assertThisInitialized2.default)(t), 'boxNode', (0, _react.createRef)()),
        t
      );
    }
    return (
      (0, _inherits2.default)(l, e),
      (0, _createClass2.default)(l, [
        {
          key: 'render',
          value: function() {
            var e,
              t = this.props,
              r = t.alignContent,
              i = t.alignItems,
              a = t.alignSelf,
              l = t.boxSizing,
              o = t.children,
              n = t.className,
              d = t.display,
              u = t.element,
              f = t.flex,
              p = t.flexBasis,
              s = t.flexDirection,
              c = t.flexGrow,
              _ = t.flexShrink,
              m = t.flexWrap,
              g = t.justifyContent,
              h = t.margin,
              b = t.marginHorizontal,
              y = void 0 === b ? h : b,
              q = t.marginVertical,
              x = void 0 === q ? h : q,
              v = t.marginBottom,
              P = void 0 === v ? x : v,
              R = t.marginLeft,
              C = void 0 === R ? y : R,
              D = t.marginRight,
              w = void 0 === D ? y : D,
              N = t.marginTop,
              S = void 0 === N ? x : N,
              j = t.order,
              z = t.overflow,
              B = t.overflowX,
              T = t.overflowY,
              W = t.padding,
              k = t.paddingHorizontal,
              I = void 0 === k ? W : k,
              H = t.paddingVertical,
              L = void 0 === H ? W : H,
              O = t.paddingBottom,
              V = void 0 === O ? L : O,
              G = t.paddingLeft,
              X = void 0 === G ? I : G,
              Y = t.paddingRight,
              A = void 0 === Y ? I : Y,
              E = t.paddingTop,
              M = void 0 === E ? L : E,
              F = t.style,
              J = (0, _objectWithoutProperties2.default)(t, [
                'alignContent',
                'alignItems',
                'alignSelf',
                'boxSizing',
                'children',
                'className',
                'display',
                'element',
                'flex',
                'flexBasis',
                'flexDirection',
                'flexGrow',
                'flexShrink',
                'flexWrap',
                'justifyContent',
                'margin',
                'marginHorizontal',
                'marginVertical',
                'marginBottom',
                'marginLeft',
                'marginRight',
                'marginTop',
                'order',
                'overflow',
                'overflowX',
                'overflowY',
                'padding',
                'paddingHorizontal',
                'paddingVertical',
                'paddingBottom',
                'paddingLeft',
                'paddingRight',
                'paddingTop',
                'style',
              ]),
              K = (0, _classnames.default)(
                _theme.default.box,
                ((e = {}),
                (0, _defineProperty2.default)(e, _theme.default['align-content-'.concat(r)], r),
                (0, _defineProperty2.default)(e, _theme.default['align-items-'.concat(i)], i),
                (0, _defineProperty2.default)(e, _theme.default['align-self-'.concat(a)], a),
                (0, _defineProperty2.default)(e, _theme.default['display-'.concat(d)], d),
                (0, _defineProperty2.default)(e, _theme.default['flex-direction-'.concat(s)], s),
                (0, _defineProperty2.default)(e, _theme.default['flex-wrap-'.concat(m)], m),
                (0, _defineProperty2.default)(e, _theme.default['justify-content-'.concat(g)], g),
                (0, _defineProperty2.default)(e, _theme.default['margin-bottom-'.concat(P)], 0 < P),
                (0, _defineProperty2.default)(e, _theme.default['margin-left-'.concat(C)], 0 < C),
                (0, _defineProperty2.default)(e, _theme.default['margin-right-'.concat(w)], 0 < w),
                (0, _defineProperty2.default)(e, _theme.default['margin-top-'.concat(S)], 0 < S),
                (0, _defineProperty2.default)(e, _theme.default['padding-bottom-'.concat(V)], 0 < V),
                (0, _defineProperty2.default)(e, _theme.default['padding-left-'.concat(X)], 0 < X),
                (0, _defineProperty2.default)(e, _theme.default['padding-right-'.concat(A)], 0 < A),
                (0, _defineProperty2.default)(e, _theme.default['padding-top-'.concat(M)], 0 < M),
                e),
                n,
              ),
              Q = (0, _objectSpread2.default)(
                {},
                l && { boxSizing: l },
                f && { flex: f },
                p && { flexBasis: p },
                isNaN(c) ? {} : { flexGrow: c },
                isNaN(_) ? {} : { flexShrink: _ },
                isNaN(j) ? {} : { order: j },
                z && { overflow: z },
                B && { overflowX: B },
                T && { overflowY: T },
                F,
              ),
              U = u;
            return _react.default.createElement(
              U,
              (0, _extends2.default)({ ref: this.boxNode, className: K, style: Q }, J),
              o,
            );
          },
        },
      ]),
      l
    );
  })(_react.PureComponent);
Box.defaultProps = { element: 'div', margin: 0, padding: 0 };
var _default = Box;
exports.default = _default;
