---
name: 'Check Types'
on:
  workflow_call:

jobs:
  check-types:
    if: ${{ !contains(github.head_ref, 'hotfix/') && !contains(github.event.head_commit.message, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Check types
        run: |
          yarn install --silent --frozen-lockfile
          yarn check-types
