---
name: Continuous Integration

on:
  push:
    branches:
      - next-release

concurrency:
  group: ${{ github.ref }}

jobs:
  lint-node:
    uses: ./.github/workflows/lint-node.yaml
    secrets: inherit

  test-node:
    uses: ./.github/workflows/test-node.yaml
    secrets: inherit

  check-types:
    uses: ./.github/workflows/check-types.yaml
    secrets: inherit

  deploy-components:
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on: [self-hosted, X64]
    needs: [check-types, lint-node, test-node]
    environment: production
    env:
      env: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set env
        run: cat env/${{ env.env }}/build.env >> $GITHUB_ENV
      - name: AWS Auth
        uses: teamleadercrm/teamleader-github-workflows/.github/actions/aws-auth@v1.1.0
        with:
          aws-profile: ${{ env.AWS_PROFILE }}
          role-to-assume: ${{ env.IAM_ROLE }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Build
        run: |
          yarn && yarn build:${{ env.YARN_BUILD }}
      - name: Deploy
        run: aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --profile ${{ env.AWS_PROFILE }}
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths '/*'
