---
name: Create new tag

on:
  push:
    branches:
      - master
    paths:
      - "package.json"
jobs:
  create-new-tag:
    uses: teamleadercrm/teamleader-github-workflows/.github/workflows/create-tag-node.yaml@v1.12.3
    secrets: inherit
