---
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}

jobs:
  lint-node:
    uses: ./.github/workflows/lint-node.yaml
    secrets: inherit

  test-node:
    uses: ./.github/workflows/test-node.yaml
    secrets: inherit

  check-types:
    uses: ./.github/workflows/check-types.yaml
    secrets: inherit

  lint-yaml:
    runs-on: [self-hosted, X64]
    steps:
      - uses: actions/checkout@v3
      - name: yaml lint
        run: |
          yamllint -d \
          "{
            extends: default,
            ignore: [chart/*, ci/*, nutcracker.yaml],
            rules:
              {
                line-length: disable,
                truthy:
                  {
                    allowed-values: ['true', 'false', 'on']
                  },
                comments:
                  {
                    min-spaces-from-content: 1
                  },
                braces:
                  {
                    max-spaces-inside: 1
                  },
                brackets:
                  {
                    max-spaces-inside: 1
                  }
              }
          }" .
