---
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}

jobs:
  lint-node:
    uses: teamleadercrm/teamleader-github-workflows/.github/workflows/lint-node.yaml@v1.1.0
    secrets: inherit

  lint-yaml:
    uses: teamleadercrm/teamleader-github-workflows/.github/workflows/lint-yaml.yaml@v1.1.0
    secrets: inherit

  test-node:
    uses: teamleadercrm/teamleader-github-workflows/.github/workflows/test-node.yaml@v1.1.0
    secrets: inherit

  check-types:
    uses: ./.github/workflows/check-types.yaml
    secrets: inherit
