---
name: 'Reviewer lottery'
on:
  pull_request_target:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
