---
name: 'Test Node'
on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node version to use'
        required: false
        default: 16
        type: string

defaults:
  run:
    shell: 'script -q -e -c "export TERM=xterm-256color; bash {0}"'

jobs:
  test-node:
    if: ${{ !contains(github.head_ref, 'hotfix/') && !contains(github.event.head_commit.message, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'yarn'
      - name: test
        run: yarn && yarn test
